# Generated by Django 4.0.6 on 2022-08-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('carousel_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='轮播图id')),
                ('imgPath', models.CharField(max_length=50, verbose_name='轮播图路径')),
                ('describes', models.CharField(default='暂无描述', max_length=50, verbose_name='轮播图描述')),
            ],
            options={
                'db_table': 'carousel',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='分类id')),
                ('category_name', models.CharField(max_length=20, verbose_name='分类名称')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='收藏id')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('product_id', models.IntegerField(verbose_name='商品id')),
                ('collect_time', models.BigIntegerField(verbose_name='收藏时间')),
            ],
            options={
                'db_table': 'collect',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='订单id')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('order_id', models.BigIntegerField(verbose_name='订单编号')),
                ('product_id', models.IntegerField(verbose_name='商品id')),
                ('product_price', models.FloatField(verbose_name='商品价格')),
                ('order_time', models.BigIntegerField(verbose_name='下单时间')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品id')),
                ('product_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('product_title', models.CharField(max_length=30, verbose_name='产品标题')),
                ('product_intro', models.TextField(verbose_name='商品简介')),
                ('product_picture', models.CharField(max_length=200, verbose_name='商品图片')),
                ('product_price', models.FloatField(verbose_name='商品价格')),
                ('product_selling_price', models.FloatField(verbose_name='商品实际价格')),
                ('product_num', models.IntegerField(verbose_name='商品数量')),
                ('product_sales', models.IntegerField(verbose_name='商品销量')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品图片id')),
                ('product_id', models.IntegerField(verbose_name='商品id')),
                ('product_picture', models.CharField(max_length=50, verbose_name='商品图片路径')),
                ('intro', models.TextField(verbose_name='商品描述')),
            ],
            options={
                'db_table': 'product_picture',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='购物车id')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('product_id', models.IntegerField(verbose_name='商品id')),
                ('num', models.IntegerField(verbose_name='商品数量')),
            ],
            options={
                'db_table': 'shoppingcart',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('userName', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('userPhoneNumber', models.CharField(max_length=11, verbose_name='用户手机号')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
